---
services:

###### SONARR ######
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}sonarr:/config
      - ${DATA}:/data
#    ports:
#      - 8989:8989
    restart: unless-stopped

###### RADARR ######

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}radarr:/config
      - ${DATA}:/data
#    ports:
#      - 7878:7878
    restart: unless-stopped

###### PROWLARR ######

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}prowlarr:/config
#    ports:
#      - 9696:9696
    restart: unless-stopped

###### DELUGE ######

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${CONFIGS}deluge:/config
      - ${DOWNLOADS}:/downloads
    ports:
#      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped

###### JELLYFIN ######

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}jellyfin:/config
      - ${DATA}/tv-shows:/data/tvshows
      - ${DATA}/movies:/data/movies
#    ports:
#      - 8096:8096
    restart: unless-stopped

###### NGINX PROXYMANAGER ######

  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest' 
    container_name: nginxproxymanager
    restart: unless-stopped 
    ports:
      - '81:81'
      - '80:80'
      - '443:443' 
    volumes:
      - ${CONFIGS}nginx/data:/data
      - ${CONFIGS}nginx/letsencrypt:/etc/letsencrypt 