services:

###### JELLYFIN ######

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}jellyfin:/config
      - ${DATA}/tv-shows:/data/tvshows
      - ${DATA}/movies:/data/movies
    networks:
      - netwrk
#    ports:
#      - 8096:8096
    restart: unless-stopped

networks:
  netwrk:
    driver: bridge
