services:

  portainer-ts:
    image: tailscale/tailscale:latest
    container_name: portainer-ts
    hostname: portainer
    environment:
      - TS_AUTHKEY=value
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_EXTRA_ARGS=--advertise-tags=tag:infra-services
      - TZ=Asia/Dubai
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module

###### JELLYFIN ######
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - ${CONFIGS}portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: service:portainer-ts
    restart: unless-stopped
