services:
  homepage-ts:
    image: tailscale/tailscale:latest
    container_name: homepage-ts
    hostname: homepage
    environment:
      #  - TS_AUTHKEY=value
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_EXTRA_ARGS=--accept-routes=true --advertise-tags=tag:home-admin-services
      - TZ=Asia/Dubai
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.pegasus-acrux.ts.net
      PUID: 1000
      PGID: 1000
      TZ: Asia/Dubai
    network_mode: service:homepage-ts
    volumes:
      - ${CONFIGS}homepage:/app/config
      - /mnt/media-library:/media-library
      - /mnt/immich:/immich
      - /mnt/storage:/storage
    restart: unless-stopped