---
services:

###### SONARR ######
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}sonarr:/config
      - ${SHOWS}:/tv
      - ${DOWNLOADS}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

###### SONARR ######

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}radarr:/config
      - ${MOVIES}:/movies
      - ${DOWNLOADS}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

###### PROWLARR ######

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

###### QBITTORRENT ######

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIGS}qbittorrent:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

###### JELLYFIN ######

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}jellyfin:/config
      - ${SHOWS}:/data/tvshows
      - ${MOVIES}:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

###### NGINX ######

  nginx:
      image: lscr.io/linuxserver/nginx:latest
      container_name: nginx
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Dubai
      volumes:
        - ${CONFIGS}nginx:/config
      ports:
        - 80:80
        - 443:443
      restart: unless-stopped