---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    hostname: mr-jellyflix
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
      - JELLYFIN_PublishedServerUrl=http://media-vault #optional
    volumes:
      - ${CONFIGS}jellyfin:/config
      - ${DATA_TV}:/data/tvshows
      - ${DATA_MOVIES}:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped