services:

  prowlarr-ts:
    image: tailscale/tailscale:latest
    container_name: prowlarr-ts
    hostname: prowlarr
    environment:
      - TS_AUTHKEY=value
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/server-helm.json
      - TZ=Asia/Dubai
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module

###### PROWLARR ######

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}prowlarr:/config
    network_mode: service:prowlarr-ts
    restart: unless-stopped