services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    networks:
      - media-server_default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - media-server_default
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:5380" 
    env_file: .env
    environment:
      - VIRTUAL_HOST="pihole.home.ms"
      - TZ=Asia/Dubai
      - WEBPASSWORD=${PASSWORD}
      - PUID=1000
      - PGID=1000
      - DNS1="1.1.1.1"
      - DNS2="1.0.0.1"
      - NETWORK_ACCESS=internal
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    volumes:
      - ${CONFIGS}pihole/pihole_etc:/etc/pihole/
      - ${CONFIGS}pihole/pihole_dnsmasq:/etc/dnsmasq.d/
    restart: unless-stopped