services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    networks:
      - media-server_default
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

networks:
  network1:
    name: media-server_default
    external: true