services:

###### NGINX PROXYMANAGER ######

  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest' 
    container_name: nginxproxymanager
    restart: unless-stopped 
    ports:
      - '80:80'
      - '443:443' 
    volumes:
      - ${CONFIGS}nginx/data:/data
      - ${CONFIGS}nginx/letsencrypt:/etc/letsencrypt
    networks:
      - netwrk
      - server-media_netwrk
      - server-helm_netwrk
      - server-dashboards_netwrk

networks:
  netwrk:
    driver: bridge
  server-media_netwrk:
      external: true
  server-helm_netwrk:
      external: true
  server-dashboards_netwrk:
      external: true