services:

  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - SERVER_COUNTRIES=
    networks:
      - helm-net

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
      - WEBUI_PORT=8080 
    volumes:
      - ${CONFIGS}qbittorrent:/config
      - ${DOWNLOADS}:/downloads
    network_mode: service:gluetun
    restart: unless-stopped

networks:
  helm-net:
    external: true