services:

  protonwire:
    container_name: protonwire
    image: ghcr.io/tprasadtp/protonwire:latest
    init: true
    restart: unless-stopped
    environment:
      PROTONVPN_SERVER: "AE#9"
      DEBUG: "0"
      KILL_SWITCH: "1"
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: tmpfs
        target: /tmp
      - type: bind
        source: private.key
        target: /etc/protonwire/private-key
        read_only: true
    networks:
      - helm-net
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
      - WEBUI_PORT=8080 
    volumes:
      - ${CONFIGS}qbittorrent:/config
      - ${DOWNLOADS}:/downloads
    network_mode: service:protonwire
    restart: unless-stopped

networks:
  helm-net:
    external: true