services:
  ###### RADARR ######

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}radarr:/config
      - ${DATA_MOVIES}:/movies
      - ${DOWNLOADS}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  ###### PROWLARR ######

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  ###### SONARR ######

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}sonarr:/config
      - ${DATA_TV}:/tv
      - ${DOWNLOADS}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  ###### QBITTORRENT ######

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIGS}qbittorrent:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
