services:

  tail-connect:
    image: tailscale/tailscale:latest
    container_name: ts-helm
    hostname: ts-helm
    environment:
      - TS_AUTHKEY=value
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/server-helm.json
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}/ts-helm/state:/var/lib/tailscale
      - ${CONFIGS}/ts-helm/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module

###### SONARR ######
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}sonarr:/config
      - ${DATA}:/data
    network_mode: service:ts-helm
    restart: unless-stopped

###### RADARR ######

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}radarr:/config
      - ${DATA}:/data
    network_mode: service:ts-helm
    restart: unless-stopped

###### PROWLARR ######

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dubai
    volumes:
      - ${CONFIGS}prowlarr:/config
    network_mode: service:ts-helm
#    ports:
#      - 9696:9696
    restart: unless-stopped